# INSPIRE Simple Geoportal
#
# NGINX:
# access via "http://localhost:80/"
#
# GeoNetwork v3.x:
# access via "http://localhost:8080/geonetwork"
# default user: admin
# default password: admin
#

version: "3.1"
services:
  # NGINX - tested (TODO need .conf setup)
  web:
    image: nginx:alpine
    container_name: web
    restart: unless-stopped
    #tty: true
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./resources/nginx/site-content:/usr/share/nginx/html
      - ./resources/nginx/conf.d:/etc/nginx/conf.d
      - ./resources/nginx/ssl:/etc/ssl
      # logs
      - ./resources/nginx/logs:/var/log/nginx
    networks:
      - geonet

  # PostGIS 
  postgis:
    image: postgis/postgis
    container_name: postgis
    restart: unless-stopped
    #tty: true
    ports:
      - 5432:5432
    volumes:
      - postgis_vol:/var/lib/postgresql
    networks:
      - geonet

  # GeoNetwork v3.x
  geonetwork3:
    image: geonetwork:3
    container_name: geonetwork3
    #restart: always
    #depends_on:
    #  - postgis
    ports:
      - 8081:8080
    environment:
      - DATA_DIR=/var/lib/geonetwork/data
      - GEONETWORK_DB_NAME=/var/lib/geonetwork/db/gn
      - JAVA_OPTS=-Djava.security.egd=file:/dev/./urandom -Djava.awt.headless=true -server -Xms2g -Xmx4g -XX:+UseConcMarkSweepGC
    volumes:
      - geonetwork_data_vol:/var/lib/geonetwork/data
      - geonetwork_db_vol:/var/lib/geonetwork/db
    networks:
      - geonet

networks:
  geonet:
    driver: bridge

volumes:
  nginx_www_vol:
  nginx_cfg_vol:
  postgis_vol:
    external:
      name: postgis_persist_volume
  geonetwork_data_vol:
    external:
      name: gn_data_persist_volume
  geonetwork_db_vol:
    external:
      name: gn_db_persist_volume
